import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialAllTables1759814305678 implements MigrationInterface {
    name = 'InitialAllTables1759814305678'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`Promotions\` (\`PromotionID\` int NOT NULL AUTO_INCREMENT, \`PromotionName\` varchar(100) NOT NULL, \`PromotionCode\` varchar(20) NULL, \`Description\` varchar(500) NULL, \`DiscountType\` varchar(20) NOT NULL, \`DiscountValue\` decimal(10,2) NOT NULL, \`StartDate\` datetime NOT NULL, \`EndDate\` datetime NOT NULL, \`UsageLimit\` int NULL, \`CurrentUsage\` int NOT NULL DEFAULT '0', \`MinPurchaseAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`IsActive\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_b4b17e9d4720b248d6d083a86e\` (\`PromotionCode\`), PRIMARY KEY (\`PromotionID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PaymentMethods\` (\`PaymentMethodID\` int NOT NULL AUTO_INCREMENT, \`MethodName\` varchar(50) NOT NULL, \`Description\` varchar(255) NULL, \`IsActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`PaymentMethodID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Studios\` (\`StudioID\` int NOT NULL AUTO_INCREMENT, \`StudioName\` varchar(100) NOT NULL, \`Country\` varchar(50) NULL, \`Description\` varchar(500) NULL, PRIMARY KEY (\`StudioID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Genres\` (\`GenreID\` int NOT NULL AUTO_INCREMENT, \`GenreName\` varchar(50) NOT NULL, \`Description\` varchar(255) NULL, PRIMARY KEY (\`GenreID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Movie_Genres\` (\`MovieID\` int NOT NULL, \`GenreID\` int NOT NULL, PRIMARY KEY (\`MovieID\`, \`GenreID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Actors\` (\`ActorID\` int NOT NULL AUTO_INCREMENT, \`ActorName\` varchar(100) NOT NULL, \`DateOfBirth\` date NULL, \`Nationality\` varchar(50) NULL, \`Biography\` varchar(1000) NULL, \`ImageURL\` varchar(255) NULL, PRIMARY KEY (\`ActorID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Movie_Actors\` (\`MovieID\` int NOT NULL, \`ActorID\` int NOT NULL, \`Role\` varchar(100) NULL, PRIMARY KEY (\`MovieID\`, \`ActorID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Directors\` (\`DirectorID\` int NOT NULL AUTO_INCREMENT, \`DirectorName\` varchar(100) NOT NULL, \`DateOfBirth\` date NULL, \`Nationality\` varchar(50) NULL, \`Biography\` varchar(1000) NULL, \`ImageURL\` varchar(255) NULL, PRIMARY KEY (\`DirectorID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Movie_Directors\` (\`MovieID\` int NOT NULL, \`DirectorID\` int NOT NULL, PRIMARY KEY (\`MovieID\`, \`DirectorID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Reviews\` (\`ReviewID\` int NOT NULL AUTO_INCREMENT, \`MovieID\` int NOT NULL, \`UserID\` int NOT NULL, \`Rating\` int NOT NULL, \`Comment\` varchar(500) NULL, \`ReviewDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`IsApproved\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_db1f4d63a87485b44588fed319\` (\`MovieID\`, \`UserID\`), PRIMARY KEY (\`ReviewID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Movies\` (\`MovieID\` int NOT NULL AUTO_INCREMENT, \`Title\` varchar(255) NOT NULL, \`OriginalTitle\` varchar(255) NULL, \`Synopsis\` varchar(2000) NOT NULL, \`Duration\` int NOT NULL, \`ReleaseDate\` date NOT NULL, \`EndDate\` date NULL, \`Rating\` decimal(3,1) NULL, \`PosterURL\` varchar(255) NULL, \`TrailerURL\` varchar(255) NULL, \`AgeRestriction\` varchar(10) NULL, \`StudioID\` int NULL, \`Status\` varchar(20) NOT NULL DEFAULT 'Upcoming', \`IsActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`MovieID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Cities\` (\`CityID\` int NOT NULL AUTO_INCREMENT, \`CityName\` varchar(100) NOT NULL, \`IsActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`CityID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Cinemas\` (\`CinemaID\` int NOT NULL AUTO_INCREMENT, \`CinemaName\` varchar(100) NOT NULL, \`Address\` varchar(255) NOT NULL, \`CityID\` int NOT NULL, \`Description\` varchar(500) NULL, \`OpenTime\` time NULL, \`CloseTime\` time NULL, \`Phone\` varchar(20) NULL, \`Email\` varchar(100) NULL, \`ImageURL\` varchar(255) NULL, \`IsActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`CinemaID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`SeatTypes\` (\`SeatTypeID\` int NOT NULL AUTO_INCREMENT, \`TypeName\` varchar(50) NOT NULL, \`PriceMultiplier\` decimal(3,2) NOT NULL DEFAULT '1.00', \`Description\` varchar(255) NULL, PRIMARY KEY (\`SeatTypeID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Seats\` (\`SeatID\` int NOT NULL AUTO_INCREMENT, \`RoomID\` int NOT NULL, \`SeatRow\` varchar(5) NOT NULL, \`SeatNumber\` varchar(5) NOT NULL, \`SeatTypeID\` int NOT NULL, \`Status\` varchar(20) NOT NULL DEFAULT 'Active', UNIQUE INDEX \`IDX_4b65d80bbee1caa322c51642ed\` (\`RoomID\`, \`SeatRow\`, \`SeatNumber\`), PRIMARY KEY (\`SeatID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Rooms\` (\`RoomID\` int NOT NULL AUTO_INCREMENT, \`RoomName\` varchar(50) NOT NULL, \`CinemaID\` int NOT NULL, \`Capacity\` int NOT NULL, \`RoomType\` varchar(50) NOT NULL, \`IsActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`RoomID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Showtimes\` (\`ShowtimeID\` int NOT NULL AUTO_INCREMENT, \`MovieID\` int NOT NULL, \`RoomID\` int NOT NULL, \`ShowDate\` date NOT NULL, \`StartTime\` time NOT NULL, \`EndTime\` time NOT NULL, \`LanguageVersion\` varchar(50) NULL, \`ScreenFormat\` varchar(50) NULL, \`BasePrice\` decimal(10,2) NOT NULL, \`Status\` varchar(20) NOT NULL DEFAULT 'Available', \`IsActive\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_917223bec22ed76667b4a89eaf\` (\`RoomID\`, \`ShowDate\`, \`StartTime\`), PRIMARY KEY (\`ShowtimeID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Tickets\` (\`TicketID\` int NOT NULL AUTO_INCREMENT, \`OrderID\` int NOT NULL, \`ShowtimeID\` int NOT NULL, \`SeatID\` int NOT NULL, \`TicketPrice\` decimal(10,2) NOT NULL, \`TicketCode\` varchar(20) NOT NULL, \`IsUsed\` tinyint NOT NULL DEFAULT 0, \`IsRefunded\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_116b54c0a444975e3e1f06151a\` (\`ShowtimeID\`, \`SeatID\`), UNIQUE INDEX \`IDX_6eb656b302f2f1f29aee37e83f\` (\`TicketCode\`), PRIMARY KEY (\`TicketID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Concessions\` (\`ConcessionID\` int NOT NULL AUTO_INCREMENT, \`Name\` varchar(100) NOT NULL, \`Description\` varchar(255) NULL, \`Price\` decimal(10,2) NOT NULL, \`Category\` varchar(50) NOT NULL, \`ImageURL\` varchar(255) NULL, \`IsAvailable\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`ConcessionID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`OrderConcessions\` (\`OrderConcessionID\` int NOT NULL AUTO_INCREMENT, \`OrderID\` int NOT NULL, \`ConcessionID\` int NOT NULL, \`Quantity\` int NOT NULL, \`UnitPrice\` decimal(10,2) NOT NULL, \`TotalPrice\` decimal(10,2) NOT NULL, PRIMARY KEY (\`OrderConcessionID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PointHistory\` (\`PointHistoryID\` int NOT NULL AUTO_INCREMENT, \`UserID\` int NOT NULL, \`Points\` int NOT NULL, \`Description\` varchar(255) NULL, \`TransactionDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`OrderID\` int NULL, PRIMARY KEY (\`PointHistoryID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Orders\` (\`OrderID\` int NOT NULL AUTO_INCREMENT, \`UserID\` int NOT NULL, \`OrderDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`TotalAmount\` decimal(10,2) NOT NULL, \`DiscountAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`FinalAmount\` decimal(10,2) NOT NULL, \`PromotionID\` int NULL, \`PaymentMethodID\` int NOT NULL, \`PaymentStatus\` varchar(20) NOT NULL DEFAULT 'Pending', \`OrderStatus\` varchar(20) NOT NULL DEFAULT 'Pending', \`TransactionCode\` varchar(50) NULL, PRIMARY KEY (\`OrderID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Notifications\` (\`NotificationID\` int NOT NULL AUTO_INCREMENT, \`UserID\` int NOT NULL, \`Title\` varchar(100) NOT NULL, \`Message\` varchar(500) NOT NULL, \`NotificationType\` varchar(50) NOT NULL, \`IsRead\` tinyint NOT NULL DEFAULT 0, \`CreatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`NotificationID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`SystemLogs\` (\`LogID\` int NOT NULL AUTO_INCREMENT, \`LogType\` varchar(50) NOT NULL, \`LogMessage\` varchar(500) NOT NULL, \`LogDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`UserID\` int NULL, \`IPAddress\` varchar(50) NULL, \`UserAgent\` varchar(255) NULL, PRIMARY KEY (\`LogID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Users\` (\`userID\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(50) NOT NULL, \`password\` varchar(255) NOT NULL, \`fullName\` varchar(100) NOT NULL, \`email\` varchar(100) NOT NULL, \`phone\` varchar(20) NULL, \`dateOfBirth\` date NULL, \`address\` varchar(255) NULL, \`membershipLevel\` varchar(20) NOT NULL DEFAULT 'Standard', \`points\` int NOT NULL DEFAULT '0', \`registrationDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`lastLogin\` datetime NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_ffc81a3b97dcbf8e320d5106c0\` (\`username\`), UNIQUE INDEX \`IDX_3c3ab3f49a87e6ddb607f3c494\` (\`email\`), PRIMARY KEY (\`userID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`SystemSettings\` (\`SettingID\` int NOT NULL AUTO_INCREMENT, \`SettingKey\` varchar(50) NOT NULL, \`SettingValue\` varchar(500) NOT NULL, \`Description\` varchar(255) NULL, \`UpdatedDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_81c84cfafcbf36eea16d44b2cd\` (\`SettingKey\`), PRIMARY KEY (\`SettingID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Banners\` (\`BannerID\` int NOT NULL AUTO_INCREMENT, \`Title\` varchar(255) NOT NULL, \`Description\` varchar(500) NULL, \`ImageURL\` varchar(255) NOT NULL, \`MobileImageURL\` varchar(255) NULL, \`LinkURL\` varchar(255) NULL, \`BannerType\` varchar(50) NOT NULL, \`MovieID\` int NULL, \`PromotionID\` int NULL, \`DisplayOrder\` int NOT NULL DEFAULT '1', \`StartDate\` datetime NOT NULL, \`EndDate\` datetime NOT NULL, \`IsActive\` tinyint NOT NULL DEFAULT 1, \`CreatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`UpdatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`BannerID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`Movie_Genres\` ADD CONSTRAINT \`FK_91ff2fe2d9a869c3878fa59cbee\` FOREIGN KEY (\`MovieID\`) REFERENCES \`Movies\`(\`MovieID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Movie_Genres\` ADD CONSTRAINT \`FK_21cf3d81c6d998a80443a4e3b74\` FOREIGN KEY (\`GenreID\`) REFERENCES \`Genres\`(\`GenreID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Movie_Actors\` ADD CONSTRAINT \`FK_6d85406c29c35a82fd478539f7c\` FOREIGN KEY (\`MovieID\`) REFERENCES \`Movies\`(\`MovieID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Movie_Actors\` ADD CONSTRAINT \`FK_0ba64c3bf115b84652d8dc5854f\` FOREIGN KEY (\`ActorID\`) REFERENCES \`Actors\`(\`ActorID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Movie_Directors\` ADD CONSTRAINT \`FK_92ac7eab5012e16b57c77db692d\` FOREIGN KEY (\`MovieID\`) REFERENCES \`Movies\`(\`MovieID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Movie_Directors\` ADD CONSTRAINT \`FK_7f20790473de31eafcd02fcca02\` FOREIGN KEY (\`DirectorID\`) REFERENCES \`Directors\`(\`DirectorID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Reviews\` ADD CONSTRAINT \`FK_0d4d2a9a88d269bcf7c2f6592e2\` FOREIGN KEY (\`MovieID\`) REFERENCES \`Movies\`(\`MovieID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Reviews\` ADD CONSTRAINT \`FK_14293f6e0f6845db9f308b6d17c\` FOREIGN KEY (\`UserID\`) REFERENCES \`Users\`(\`userID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Movies\` ADD CONSTRAINT \`FK_e7caf85e2a254f457b070fa1995\` FOREIGN KEY (\`StudioID\`) REFERENCES \`Studios\`(\`StudioID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Cinemas\` ADD CONSTRAINT \`FK_bc845322ebeccd82bdcd6bf9e17\` FOREIGN KEY (\`CityID\`) REFERENCES \`Cities\`(\`CityID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Seats\` ADD CONSTRAINT \`FK_5197a239517a3dbff44af5b16f0\` FOREIGN KEY (\`RoomID\`) REFERENCES \`Rooms\`(\`RoomID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Seats\` ADD CONSTRAINT \`FK_7898783b7ec74a08125490fcc39\` FOREIGN KEY (\`SeatTypeID\`) REFERENCES \`SeatTypes\`(\`SeatTypeID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Rooms\` ADD CONSTRAINT \`FK_f019e8383e59966aa98c8989919\` FOREIGN KEY (\`CinemaID\`) REFERENCES \`Cinemas\`(\`CinemaID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Showtimes\` ADD CONSTRAINT \`FK_f9a6cdd13c553f4d5379c8a44d1\` FOREIGN KEY (\`MovieID\`) REFERENCES \`Movies\`(\`MovieID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Showtimes\` ADD CONSTRAINT \`FK_b44e4a597ee2b846ee7f45f0108\` FOREIGN KEY (\`RoomID\`) REFERENCES \`Rooms\`(\`RoomID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Tickets\` ADD CONSTRAINT \`FK_c75e8a2b845b12dc213f2b70f0c\` FOREIGN KEY (\`OrderID\`) REFERENCES \`Orders\`(\`OrderID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Tickets\` ADD CONSTRAINT \`FK_e3f268986188518b386544b1679\` FOREIGN KEY (\`ShowtimeID\`) REFERENCES \`Showtimes\`(\`ShowtimeID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Tickets\` ADD CONSTRAINT \`FK_9401a57b89830cc1c373a7928f8\` FOREIGN KEY (\`SeatID\`) REFERENCES \`Seats\`(\`SeatID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`OrderConcessions\` ADD CONSTRAINT \`FK_acade3f36dcf0bf933f13e676fe\` FOREIGN KEY (\`OrderID\`) REFERENCES \`Orders\`(\`OrderID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`OrderConcessions\` ADD CONSTRAINT \`FK_5e7abc57f09b76998ac82212071\` FOREIGN KEY (\`ConcessionID\`) REFERENCES \`Concessions\`(\`ConcessionID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PointHistory\` ADD CONSTRAINT \`FK_67749352166eb13eddb774464bb\` FOREIGN KEY (\`UserID\`) REFERENCES \`Users\`(\`userID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PointHistory\` ADD CONSTRAINT \`FK_cc28288cd64d2a174382bde92d6\` FOREIGN KEY (\`OrderID\`) REFERENCES \`Orders\`(\`OrderID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Orders\` ADD CONSTRAINT \`FK_3724ce3af91688b731ab2e2f97d\` FOREIGN KEY (\`UserID\`) REFERENCES \`Users\`(\`userID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Orders\` ADD CONSTRAINT \`FK_9f40832635591121b3beac10efc\` FOREIGN KEY (\`PromotionID\`) REFERENCES \`Promotions\`(\`PromotionID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Orders\` ADD CONSTRAINT \`FK_1d0dc86ed2d6c24506ea8207a44\` FOREIGN KEY (\`PaymentMethodID\`) REFERENCES \`PaymentMethods\`(\`PaymentMethodID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Notifications\` ADD CONSTRAINT \`FK_0a132b77f27822144b818d02619\` FOREIGN KEY (\`UserID\`) REFERENCES \`Users\`(\`userID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`SystemLogs\` ADD CONSTRAINT \`FK_ccd4bc4b81b314cfb46d0992ca6\` FOREIGN KEY (\`UserID\`) REFERENCES \`Users\`(\`userID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Banners\` ADD CONSTRAINT \`FK_46b24de255c0bc9573684f1e897\` FOREIGN KEY (\`MovieID\`) REFERENCES \`Movies\`(\`MovieID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Banners\` ADD CONSTRAINT \`FK_98d7a8e17e38b00f129a56059a4\` FOREIGN KEY (\`PromotionID\`) REFERENCES \`Promotions\`(\`PromotionID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`Banners\` DROP FOREIGN KEY \`FK_98d7a8e17e38b00f129a56059a4\``);
        await queryRunner.query(`ALTER TABLE \`Banners\` DROP FOREIGN KEY \`FK_46b24de255c0bc9573684f1e897\``);
        await queryRunner.query(`ALTER TABLE \`SystemLogs\` DROP FOREIGN KEY \`FK_ccd4bc4b81b314cfb46d0992ca6\``);
        await queryRunner.query(`ALTER TABLE \`Notifications\` DROP FOREIGN KEY \`FK_0a132b77f27822144b818d02619\``);
        await queryRunner.query(`ALTER TABLE \`Orders\` DROP FOREIGN KEY \`FK_1d0dc86ed2d6c24506ea8207a44\``);
        await queryRunner.query(`ALTER TABLE \`Orders\` DROP FOREIGN KEY \`FK_9f40832635591121b3beac10efc\``);
        await queryRunner.query(`ALTER TABLE \`Orders\` DROP FOREIGN KEY \`FK_3724ce3af91688b731ab2e2f97d\``);
        await queryRunner.query(`ALTER TABLE \`PointHistory\` DROP FOREIGN KEY \`FK_cc28288cd64d2a174382bde92d6\``);
        await queryRunner.query(`ALTER TABLE \`PointHistory\` DROP FOREIGN KEY \`FK_67749352166eb13eddb774464bb\``);
        await queryRunner.query(`ALTER TABLE \`OrderConcessions\` DROP FOREIGN KEY \`FK_5e7abc57f09b76998ac82212071\``);
        await queryRunner.query(`ALTER TABLE \`OrderConcessions\` DROP FOREIGN KEY \`FK_acade3f36dcf0bf933f13e676fe\``);
        await queryRunner.query(`ALTER TABLE \`Tickets\` DROP FOREIGN KEY \`FK_9401a57b89830cc1c373a7928f8\``);
        await queryRunner.query(`ALTER TABLE \`Tickets\` DROP FOREIGN KEY \`FK_e3f268986188518b386544b1679\``);
        await queryRunner.query(`ALTER TABLE \`Tickets\` DROP FOREIGN KEY \`FK_c75e8a2b845b12dc213f2b70f0c\``);
        await queryRunner.query(`ALTER TABLE \`Showtimes\` DROP FOREIGN KEY \`FK_b44e4a597ee2b846ee7f45f0108\``);
        await queryRunner.query(`ALTER TABLE \`Showtimes\` DROP FOREIGN KEY \`FK_f9a6cdd13c553f4d5379c8a44d1\``);
        await queryRunner.query(`ALTER TABLE \`Rooms\` DROP FOREIGN KEY \`FK_f019e8383e59966aa98c8989919\``);
        await queryRunner.query(`ALTER TABLE \`Seats\` DROP FOREIGN KEY \`FK_7898783b7ec74a08125490fcc39\``);
        await queryRunner.query(`ALTER TABLE \`Seats\` DROP FOREIGN KEY \`FK_5197a239517a3dbff44af5b16f0\``);
        await queryRunner.query(`ALTER TABLE \`Cinemas\` DROP FOREIGN KEY \`FK_bc845322ebeccd82bdcd6bf9e17\``);
        await queryRunner.query(`ALTER TABLE \`Movies\` DROP FOREIGN KEY \`FK_e7caf85e2a254f457b070fa1995\``);
        await queryRunner.query(`ALTER TABLE \`Reviews\` DROP FOREIGN KEY \`FK_14293f6e0f6845db9f308b6d17c\``);
        await queryRunner.query(`ALTER TABLE \`Reviews\` DROP FOREIGN KEY \`FK_0d4d2a9a88d269bcf7c2f6592e2\``);
        await queryRunner.query(`ALTER TABLE \`Movie_Directors\` DROP FOREIGN KEY \`FK_7f20790473de31eafcd02fcca02\``);
        await queryRunner.query(`ALTER TABLE \`Movie_Directors\` DROP FOREIGN KEY \`FK_92ac7eab5012e16b57c77db692d\``);
        await queryRunner.query(`ALTER TABLE \`Movie_Actors\` DROP FOREIGN KEY \`FK_0ba64c3bf115b84652d8dc5854f\``);
        await queryRunner.query(`ALTER TABLE \`Movie_Actors\` DROP FOREIGN KEY \`FK_6d85406c29c35a82fd478539f7c\``);
        await queryRunner.query(`ALTER TABLE \`Movie_Genres\` DROP FOREIGN KEY \`FK_21cf3d81c6d998a80443a4e3b74\``);
        await queryRunner.query(`ALTER TABLE \`Movie_Genres\` DROP FOREIGN KEY \`FK_91ff2fe2d9a869c3878fa59cbee\``);
        await queryRunner.query(`DROP TABLE \`Banners\``);
        await queryRunner.query(`DROP INDEX \`IDX_81c84cfafcbf36eea16d44b2cd\` ON \`SystemSettings\``);
        await queryRunner.query(`DROP TABLE \`SystemSettings\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c3ab3f49a87e6ddb607f3c494\` ON \`Users\``);
        await queryRunner.query(`DROP INDEX \`IDX_ffc81a3b97dcbf8e320d5106c0\` ON \`Users\``);
        await queryRunner.query(`DROP TABLE \`Users\``);
        await queryRunner.query(`DROP TABLE \`SystemLogs\``);
        await queryRunner.query(`DROP TABLE \`Notifications\``);
        await queryRunner.query(`DROP TABLE \`Orders\``);
        await queryRunner.query(`DROP TABLE \`PointHistory\``);
        await queryRunner.query(`DROP TABLE \`OrderConcessions\``);
        await queryRunner.query(`DROP TABLE \`Concessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_6eb656b302f2f1f29aee37e83f\` ON \`Tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_116b54c0a444975e3e1f06151a\` ON \`Tickets\``);
        await queryRunner.query(`DROP TABLE \`Tickets\``);
        await queryRunner.query(`DROP INDEX \`IDX_917223bec22ed76667b4a89eaf\` ON \`Showtimes\``);
        await queryRunner.query(`DROP TABLE \`Showtimes\``);
        await queryRunner.query(`DROP TABLE \`Rooms\``);
        await queryRunner.query(`DROP INDEX \`IDX_4b65d80bbee1caa322c51642ed\` ON \`Seats\``);
        await queryRunner.query(`DROP TABLE \`Seats\``);
        await queryRunner.query(`DROP TABLE \`SeatTypes\``);
        await queryRunner.query(`DROP TABLE \`Cinemas\``);
        await queryRunner.query(`DROP TABLE \`Cities\``);
        await queryRunner.query(`DROP TABLE \`Movies\``);
        await queryRunner.query(`DROP INDEX \`IDX_db1f4d63a87485b44588fed319\` ON \`Reviews\``);
        await queryRunner.query(`DROP TABLE \`Reviews\``);
        await queryRunner.query(`DROP TABLE \`Movie_Directors\``);
        await queryRunner.query(`DROP TABLE \`Directors\``);
        await queryRunner.query(`DROP TABLE \`Movie_Actors\``);
        await queryRunner.query(`DROP TABLE \`Actors\``);
        await queryRunner.query(`DROP TABLE \`Movie_Genres\``);
        await queryRunner.query(`DROP TABLE \`Genres\``);
        await queryRunner.query(`DROP TABLE \`Studios\``);
        await queryRunner.query(`DROP TABLE \`PaymentMethods\``);
        await queryRunner.query(`DROP INDEX \`IDX_b4b17e9d4720b248d6d083a86e\` ON \`Promotions\``);
        await queryRunner.query(`DROP TABLE \`Promotions\``);
    }

}
